version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: devtask-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - devtask-volume:/data/db

  backend:
    build: ./backend
    container_name: devtask-backend
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: mydatabase
      MONGO_USER: myuser
      MONGO_PASSWORD: mypassword
    ports:
      - "8083:8083"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: devtask-frontend
    ports:
      - "3000:4173"
    depends_on:
      - backend

volumes:
  devtask-volume: